apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    url: postgres_jobs:5432
    database: jobs_db
    user: jobs_user
    secureJsonData:
      password: jobs_password123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true